import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google';
import './globals.css'

const inter = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Sendif | Pau Segarra',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="flex items-center flex-col bg-gray-100 py-5">
          <div className="text-[#00004c]">developed by pau<strong>segarra</strong></div>
          <div className="flex gap-5 py-5">
            <a href="https://github.com/pausegarra/sendif" target="_blank"><img src="/assets/github.svg" alt="" /></a>
          </div>
        </footer>
      </body>
    </html>
  )
}
